### ISSUE TITLE
Not appending to CSV

### ISSUE THREAD

**Issue by QuimiQ** [sbirdsill/PowerShell-PC-Inventory#2]
Hey very cool script. Thank you so much.

I have one problem though. It seems like the .csv is overwritten instead of the new information appended. As I understand it, after every log on there should be a new entry. I only ever have one entry (from the newest logon). 

I can't seem to find the error.

**Comment by hikinata** [comment]
hey, I have the same thing I think, after a while it deletes all the previous entries and starts again..

**Comment by sbirdsill** [comment]
Hi all, thanks for the report. After some testing, I discovered a race condition bug that would result in the entire CSV file being erased if more than one computer ran the script at a time. I released a new version of the script that will instead create individual CSV files for each computer it runs instead of adding it all to one CSV file.

If you specify the -c flag, the script will consolidate all the individual CSV files into one presentable CSV report. This is not the most convenient solution, but this was the only way that I could get to work to overcome this limitation in PowerShell. I experimented with doing a file lock on the CSV file, however I was unable to get this to work. I am open to improvements if you have any to contribute.

I will update the README tomorrow.
